// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeQ5J0jpPFdJeWjJ2pkPccFV3FkzUG0xE',
    appId: '1:752034908739:web:338cfde7b5540a6dcc22f6',
    messagingSenderId: '752034908739',
    projectId: 'daily-moter-wash',
    authDomain: 'daily-moter-wash.firebaseapp.com',
    storageBucket: 'daily-moter-wash.firebasestorage.app',
    measurementId: 'G-6ZTX75GMKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTJufqx_wnq5kLSRDuUEBe3puLMotaJ_c',
    appId: '1:752034908739:android:24934d66b3d41620cc22f6',
    messagingSenderId: '752034908739',
    projectId: 'daily-moter-wash',
    storageBucket: 'daily-moter-wash.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1jjQmWMq6bq60dILMSlxj_z5nBlO-j2c',
    appId: '1:752034908739:ios:76c4f78de81f1cd4cc22f6',
    messagingSenderId: '752034908739',
    projectId: 'daily-moter-wash',
    storageBucket: 'daily-moter-wash.firebasestorage.app',
    iosBundleId: 'com.app.dmw',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeQ5J0jpPFdJeWjJ2pkPccFV3FkzUG0xE',
    appId: '1:752034908739:web:63cda97321897baacc22f6',
    messagingSenderId: '752034908739',
    projectId: 'daily-moter-wash',
    authDomain: 'daily-moter-wash.firebaseapp.com',
    storageBucket: 'daily-moter-wash.firebasestorage.app',
    measurementId: 'G-4HP5XG3FXF',
  );
}
